[tool.black]
line-length = 100
target-version = ['py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | .conda
)/
'''

[tool.isort]
skip = 'docs/conf.py,__init__.py,setup.py,.ci,.conda'
default_section = 'THIRDPARTY'
known_first_party = 'proteinsolver'
# For compatibility with black
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 108
# For compatibility with vscode
verbose = false
