name: proteinsolver
channels:
  - pytorch
  - conda-forge
  - defaults
  - ostrokach-forge
  - kimlab
  - bioconda
  - salilab
  - openbabel
dependencies:
  # Basic python
  - python =3.7
  - pip
  - tqdm
  - future
  # Numeric packages
  - numpy
  - scipy
  - pandas
  - matplotlib
  - pyarrow
  - numba
  - cython
  - h5py
  # Machine learning
  - scikit-learn
  - lightgbm
  - cudatoolkit =10.*
  - pytorch >=1.3
  - torchvision
  - torch-geometric
  - tensorflow
  - tensorboard
  # Geometric
  - networkx
  # Biology
  - biopython
  - modeller
  - kmbio
  - kmtools
  # Interactive notebooks
  - ipython
  - ipykernel
  - ipywidgets
  - notebook
  - papermill
  # Development tools (required by e.g. pytorch-geometric)
  - pytest
  - pytest-runner
  - pytest-cov
  - black
  - isort
  # AWS
  # Google Cloud
  - google-cloud-storage
  - gcsfs
  # Proteinsolver
  - ruamel.yaml >=0.16.0
